[database]
url = "file://gestalt.db"
user = "root"
pass = "root"
namespace = "gestalt"
database = "timeline"

[cognition]
# Default model (Claude 3.5 Sonnet)
model_id = "anthropic.claude-3-5-sonnet-20240620-v1:0"

[agent]
id = "cli_default"

[telegram]
# bot_token = "YOUR_TOKEN_HERE"
# allowed_users = ["username1"]
